import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#09080C',
    position: 'relative',
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  topCurve: {
    position: 'absolute',
    top: -height * 0.4,
    left: -width * 0.3,
    width: width * 0.8,
    height: height * 0.6,
    borderRadius: width * 0.4,
    borderWidth: 2,
    borderColor: '#FB923C',
    opacity: 0.15,
    transform: [{ rotate: '-20deg' }],
  },
  bottomCurve: {
    position: 'absolute',
    bottom: -height * 0.5,
    right: -width * 0.4,
    width: width * 1.3,
    height: height * 0.9,
    borderRadius: width * 0.65,
    borderWidth: 2,
    borderColor: '#00FFD4',
    opacity: 0.2,
    transform: [{ rotate: '30deg' }],
  },
  decorativeCurve1: {
    position: 'absolute',
    top: height * 0.05,
    left: -width * 0.6,
    width: width * 0.9,
    height: width * 0.9,
    borderRadius: width * 0.45,
    borderWidth: 1,
    borderColor: '#4DD0E1',
    opacity: 0.1,
    transform: [{ rotate: '50deg' }],
  },
  decorativeCurve2: {
    position: 'absolute',
    bottom: height * 0.15,
    right: -width * 0.5,
    width: width * 0.7,
    height: width * 0.7,
    borderRadius: width * 0.35,
    borderWidth: 1,
    borderColor: '#26C6DA',
    opacity: 0.12,
    transform: [{ rotate: '-40deg' }],
  },
  decorativeCurve3: {
    position: 'absolute',
    top: height * 0.3,
    right: -width * 0.2,
    width: width * 0.5,
    height: width * 0.5,
    borderRadius: width * 0.25,
    borderWidth: 1,
    borderColor: '#00B8E6',
    opacity: 0.08,
    transform: [{ rotate: '15deg' }],
  },
  content: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: height * 0.15,
    paddingBottom: height * 0.08,
    zIndex: 1,
  },
  titleContainer: {
    alignItems: 'center',
    marginTop: height * 0.1,
  },
  titleText: {
    fontSize: 64,
    fontWeight: 'bold',
    color: '#FB923C',
    textAlign: 'center',
    letterSpacing: 6,
    textShadowColor: '#00D4FF',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
    marginBottom: 8,
  },
  subtitleText: {
    fontSize: 48,
    fontWeight: '600',
    color: '#00FFD4',
    textAlign: 'center',
    letterSpacing: 3,
    textShadowColor: '#00FFD4',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  buttonContainer: {
    width: '100%',
    alignItems: 'center',
    gap: 16,
  },
  importButton: {
    width: '100%',
    maxWidth: 320,
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 25,
    backgroundColor: 'rgba(26, 23, 32, 0.8)',
    borderWidth: 1.5,
    borderColor: '#FB923C',
    shadowColor: '#00D4FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  importButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FB923C',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  createButton: {
    width: '100%',
    maxWidth: 320,
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 25,
    backgroundColor: '#F59E0B',
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 12,
    // Gradient effect simulation with multiple layers
    borderWidth: 0,
  },
  createButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#09080C',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
});
