import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#09080C', // Updated to match new dark theme primary
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  topCurve: {
    position: 'absolute',
    top: -height * 0.3,
    left: -width * 0.2,
    width: width * 0.8,
    height: height * 0.6,
    borderRadius: width * 0.4,
    borderWidth: 2,
    borderColor: '#FB923C',
    opacity: 0.3,
    transform: [{ rotate: '-15deg' }],
  },
  bottomCurve: {
    position: 'absolute',
    bottom: -height * 0.4,
    right: -width * 0.3,
    width: width * 1.2,
    height: height * 0.8,
    borderRadius: width * 0.6,
    borderWidth: 2,
    borderColor: '#F59E0B',
    opacity: 0.4,
    transform: [{ rotate: '25deg' }],
  },
  decorativeCurve1: {
    position: 'absolute',
    top: height * 0.1,
    left: -width * 0.5,
    width: width * 0.7,
    height: width * 0.7,
    borderRadius: width * 0.35,
    borderWidth: 1,
    borderColor: '#FDBA74',
    opacity: 0.2,
    transform: [{ rotate: '45deg' }],
  },
  decorativeCurve2: {
    position: 'absolute',
    bottom: height * 0.2,
    right: -width * 0.4,
    width: width * 0.6,
    height: width * 0.6,
    borderRadius: width * 0.3,
    borderWidth: 1,
    borderColor: '#FED7AA',
    opacity: 0.25,
    transform: [{ rotate: '-30deg' }],
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    zIndex: 1,
  },
  logoContainer: {
    marginBottom: 40,
    shadowColor: '#FB923C',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.8,
    shadowRadius: 25,
    elevation: 25,
  },
  textContainer: {
    alignItems: 'center',
  },
  titleText: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#FB923C',
    textAlign: 'center',
    letterSpacing: 4,
    textShadowColor: '#FB923C',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
    marginBottom: 8,
  },
  subtitleText: {
    fontSize: 36,
    fontWeight: '600',
    color: '#F59E0B',
    textAlign: 'center',
    letterSpacing: 2,
    textShadowColor: '#F59E0B',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  loadingContainer: {
    position: 'absolute',
    bottom: 80,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FB923C',
    marginHorizontal: 4,
    opacity: 0.7,
  },
  loadingDotDelay1: {
    backgroundColor: '#FDBA74',
  },
  loadingDotDelay2: {
    backgroundColor: '#F59E0B',
  },
  particle: {
    position: 'absolute',
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#FB923C',
    opacity: 0.6,
    left: 0,
    top: 0,
  },
  particle1: {
    position: 'absolute',
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: '#FDBA74',
    opacity: 0.5,
    left: 0,
    top: 0,
  },
  particle2: {
    position: 'absolute',
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#F59E0B',
    opacity: 0.4,
    left: 0,
    top: 0,
  },
  // Gradient orbs
  gradientOrb1: {
    position: 'absolute',
    top: height * 0.1,
    left: width * 0.1,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#FB923C',
    opacity: 0.3,
  },
  gradientOrb2: {
    position: 'absolute',
    top: height * 0.6,
    right: width * 0.15,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F59E0B',
    opacity: 0.2,
  },
  gradientOrb3: {
    position: 'absolute',
    bottom: height * 0.2,
    left: width * 0.2,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#FDBA74',
    opacity: 0.25,
  },
  // Geometric shapes
  geometricShape1: {
    position: 'absolute',
    width: 40,
    height: 40,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#FB923C',
    opacity: 0.15,
    left: 0,
    top: 0,
  },
  geometricShape2: {
    position: 'absolute',
    width: 30,
    height: 30,
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: '#F59E0B',
    borderRadius: 15,
    opacity: 0.12,
    left: 0,
    top: 0,
  },
  // Pulse elements
  pulseElement: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#FB923C',
    opacity: 0.1,
    left: width * 0.5 - 100,
    top: height * 0.5 - 100,
  },
});
